### ISSUE TITLE
🌟TODO

### ISSUE THREAD

**Issue by ak0327** [ak0327/minirt_rev0#13]
- Mandatory要件
  - [x] 3 simple geometric objects: plane, sphere, cylinder
  - [x] Light management: spot brightness, ambiance lighting
  - [x] Window management: ESC, (x)ボタンでwindowを閉じる
- Bonus要件
  - [x] 完全鏡面反射(Phongの反射モデル)
  - [x] 2nd-degree object : 円錐 #7 
  - [x] multi-spotlight #8 
  - [x] checker board texture #5 
  - [x] bump map texture #9 
- Mandatory & Bonus共通
  - [x] rfファイルの読み取り #10 
  - [x] free
  - [ ] norm
  - [ ] error handling
  - [ ] #17
- 努力目標
  - [ ] 透過・屈折の実装 #6 
  - [ ] 2nd-degree object : paraboloid, hyperboloid, etc
- Bugfix/Refactor
  - [x] #15
  - [x] #16 
  - [x] #20 
- Pending
  * #11
  * #12
  * #18 
  * #23

**Comment by ak0327** [comment]
Memo
* 2d-object
  - cornのr-hを二次関数で表現すれば、paraboloidができそう
  - 形状はcornの小改造で済むが、法線ベクトルが面倒かも
  - hyperboloidはわからん
